---
title: "About"
---

Welcome to my website! I am an exposure scientist in training with an interest in psychosocial exposures in the workplace: what they are, how to measure them, how they interact with physical exposures in the workplace, and how to determine if they are causally linked to health outcomes.

I am particularly interested in the working conditions and health outcomes of people who drive for a living. Through my dissertation research, I hope to clarify the health impacts of a specific subset of occupational driving - drivers who are subject to algorithmic control and the gamification of work (for example, rideshare drivers and Amazon delivery drivers).

## Education

PhD, [Environmental Health](publichealth.jhu.edu/departments/environmental-health-and-engineering) \| Johns Hopkins School of Public Health \| Expected 2029

MPH \| Johns Hopkins School of Public Health \| 2019

## Experience

#### Baltimore, Maryland, USA

Program Officer \| [Digitunity](www.digitunity.org) \| 2022-2025

Staff Member \| Office of Equity at Baltimore City Public School System \| 2019-2021

#### New Delhi, India

Programs Associate \| [TARSHI](www.tarshi.net) \| 2016-2018

#### Jaipur, Rajasthan, India

Fellow \| [International Innovation Corps](www.iic.uchicago.edu/) \| 2015-2016
